language: scala
sudo: false
jdk:
  - oraclejdk8

scala:
  - 2.11.8

env:
  - vars="-Dhadoop.version=2.6.0 -Dspark.version=2.1.0 -Dcoveralls.disable=1"
  - vars=""

script: sbt $vars ++$TRAVIS_SCALA_VERSION clean coverage test

cache:
  directories:
  - \$HOME/.ivy2/cache
  - \$HOME/.sbt/boot/
  - \$HOME/.zinc

after_success: bash <(curl -s https://codecov.io/bash)

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find \$HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find \$HOME/.sbt -name "*.lock" -delete
